
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.util.Scanner;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author milin
 */
public class customer extends javax.swing.JFrame {

    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
        showDate();
        showTime();
        auto_id();
        to.requestFocus();
    }
    
    void showDate()
    {
       Date d =new Date();
       SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
       autodate.setText(s.format(d));
     }
    
    void showTime()
    {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                time.setText(s.format(d));
            }
        }
        ).start();
    }
    
    public void auto_id(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/milind?autoRecoonect=true&useSSL=false","root","");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select Max(id) from record");
            rs.next();
            rs.getString("Max(id)");
            if(rs.getString("Max(id)")==null){
                id.setText("001");
            }
            else{
                Long ID = Long.parseLong(rs.getString("Max(id)").substring(2,rs.getString("Max(id)").length()));
                ID++;
                id.setText(""+String.format("%03d",ID));
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
    }
    
    Connection con ;
    PreparedStatement insert;
    ResultSet rs;
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        autodate = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gstno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        challan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        ratepertrip = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        sgst = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        sgstamt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cgst = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cgstamt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        grandAmount = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        vehiclecode = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        vehicleno = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        print = new javax.swing.JButton();
        totaltrip = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        to = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billtxt = new javax.swing.JTextArea();
        search = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_customer-removebg-preview.png"))); // NOI18N
        jLabel1.setText("ADD CUSTOMERS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 13, 285, 99));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("BILL ID :-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, -1, -1));

        id.setEditable(false);
        id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 69, 116, -1));

        autodate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        autodate.setForeground(new java.awt.Color(0, 0, 204));
        autodate.setText("Date\n");
        getContentPane().add(autodate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 13, -1, -1));

        time.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        time.setForeground(new java.awt.Color(0, 51, 153));
        time.setText("Time");
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close lgo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1403, 10, 47, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimize logo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1341, 10, 44, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Address :-");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 193, -1, -1));

        address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 187, 258, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("GSTIN :-");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        gstno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gstno.setText("\n");
        gstno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstnoActionPerformed(evt);
            }
        });
        getContentPane().add(gstno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Date :-");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Challan No :-");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        challan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        challan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                challanKeyTyped(evt);
            }
        });
        getContentPane().add(challan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 230, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("Total Trip :-");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("Rate Per Trip :-");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("Amount :-");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        amount.setEditable(false);
        amount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 230, -1));

        ratepertrip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ratepertrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratepertripActionPerformed(evt);
            }
        });
        ratepertrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ratepertripKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ratepertripKeyTyped(evt);
            }
        });
        getContentPane().add(ratepertrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 230, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("SGST :-");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, -1));

        sgst.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sgst.setText("0");
        sgst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sgstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sgstFocusLost(evt);
            }
        });
        sgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgstActionPerformed(evt);
            }
        });
        sgst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sgstKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sgstKeyTyped(evt);
            }
        });
        getContentPane().add(sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 69, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("%");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        sgstamt.setEditable(false);
        sgstamt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(sgstamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 230, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 204));
        jLabel16.setText("Amount :-");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 153));
        jLabel17.setText("CGST :-");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, -1));

        cgst.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cgst.setText("0");
        cgst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cgstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cgstFocusLost(evt);
            }
        });
        cgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgstActionPerformed(evt);
            }
        });
        cgst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cgstKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cgstKeyTyped(evt);
            }
        });
        getContentPane().add(cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 68, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 204));
        jLabel18.setText("%");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 204));
        jLabel19.setText("Amount:-");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, -1));

        cgstamt.setEditable(false);
        cgstamt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cgstamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgstamtActionPerformed(evt);
            }
        });
        getContentPane().add(cgstamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 230, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("Grand Amount :-");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, -1, -1));

        grandAmount.setEditable(false);
        grandAmount.setBackground(new java.awt.Color(0, 204, 204));
        grandAmount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        grandAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandAmountActionPerformed(evt);
            }
        });
        getContentPane().add(grandAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 230, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 204));
        jLabel21.setText("Contact No :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 133, -1, -1));

        contact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactKeyTyped(evt);
            }
        });
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 234, -1));

        save.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        save.setForeground(new java.awt.Color(0, 51, 153));
        save.setText("SAVE");
        save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 130, 51));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 204));
        jLabel22.setText("Vehicle Code:-");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        vehiclecode.setBackground(new java.awt.Color(51, 204, 0));
        vehiclecode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vehiclecode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vehiclecodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vehiclecodeKeyTyped(evt);
            }
        });
        getContentPane().add(vehiclecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 121, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 204));
        jLabel23.setText("Vehicle No. :-");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        vehicleno.setEditable(false);
        vehicleno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(vehicleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 230, -1));

        home.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        home.setForeground(new java.awt.Color(255, 51, 51));
        home.setText("HOME");
        home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 730, 120, 51));

        print.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        print.setForeground(new java.awt.Color(0, 51, 153));
        print.setText("PRINT");
        print.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, 132, 53));

        totaltrip.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totaltrip.setText("0");
        totaltrip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                totaltripFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                totaltripFocusLost(evt);
            }
        });
        totaltrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltripActionPerformed(evt);
            }
        });
        totaltrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totaltripKeyTyped(evt);
            }
        });
        getContentPane().add(totaltrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 120, -1));

        reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 51, 153));
        reset.setText("RESET");
        reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 730, 130, 54));

        to.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        to.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                toKeyTyped(evt);
            }
        });
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 260, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("To:-");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        billtxt.setEditable(false);
        billtxt.setColumns(20);
        billtxt.setRows(5);
        jScrollPane1.setViewportView(billtxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 79, 729, 710));

        search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search.setText("Search by Name");
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 220, 40));

        searchbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(0, 51, 204));
        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 130, 40));

        delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 51, 153));
        delete.setText("DELETE");
        delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 730, 130, 54));

        update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(0, 51, 153));
        update.setText("UPDATE");
        update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 660, 120, 54));

        date.setDateFormatString("dd/MM/yyyy");
        date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 250, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to CLOSE","EXIT",
                JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_toActionPerformed

    private void gstnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gstnoActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_amountActionPerformed

    
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
  
            
        
        
        if(emptyvalue() & contactvalidate()){
        
        String Id = id.getText();
        String Name = to.getText();
        String Contact = contact.getText();
        String Address = address.getText();
        String Gst= gstno.getText();
        SimpleDateFormat Dformat = new SimpleDateFormat("dd/MM/yyy");
        String Date = Dformat.format(date.getDate());
        String Challan = challan.getText();
        String VehicleCode = vehiclecode.getText();
        String VehicleNo = vehicleno.getText();
        String RatePerTrip = ratepertrip.getText();
        String TotalTrip = totaltrip.getText();
        String Subamount= amount.getText();
        String Cgst = cgst.getText();
        String CgstAmt= cgstamt.getText();
        String Sgst = sgst.getText();
        String SgstAmt = sgstamt.getText();
        String GrandAmount = grandAmount.getText(); 
        
        try{
             Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/milind?autoRecoonect=true&useSSL=false","root","");
            insert = con.prepareStatement("insert into record(id,customerName,contact,address,gst,date,challan,vehiclecode,vehicleno,ratepertrip,totaltrip,subamount,sgst,sgstamt,cgst,cgstamt,grandamount)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            insert.setString(1, Id);
            insert.setString(2, Name);
            insert.setString(3, Contact);
            insert.setString(4, Address);
            insert.setString(5, Gst);
            insert.setString(6, Date);
            insert.setString(7,Challan);
            insert.setString(8, VehicleCode);
            insert.setString(9, VehicleNo);
            insert.setString(10, RatePerTrip);
            insert.setString(11, TotalTrip);
            insert.setString(12, Subamount);
            insert.setString(13, Sgst);
            insert.setString(14, SgstAmt);
            insert.setString(15,Cgst);
            insert.setString(16, CgstAmt);
            insert.setString(17,GrandAmount); 
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "RECORD SAVED !!!!");
        }
       
           catch (ClassNotFoundException ex) {
                Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
            }
        
          catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Can Not Save Duplicate Record!!!!","Warning",JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void ratepertripKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ratepertripKeyPressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_ratepertripKeyPressed

    private void sgstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sgstKeyPressed
        // TODO add your handling code here:
              
    }//GEN-LAST:event_sgstKeyPressed

    private void sgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgstActionPerformed
        // TODO add your handling code here:
        
        if(amount.getText().isEmpty() && sgst.getText().isEmpty() )
           {
               JOptionPane.showMessageDialog(null,"Please check Details");
           }
           else
           {
               try
               {
                   int Sgst = Integer.parseInt(sgst.getText().toString());
                   int Amount = Integer.parseInt(amount.getText().toString());
                   int GrandTotal = Integer.parseInt(grandAmount.getText().toString());
                   
                   int sgstAmt = Amount * Sgst /100 ;
                   
                   sgstamt.setText(String.valueOf(sgstAmt));
                   
                   GrandTotal = Amount + sgstAmt ;
                   grandAmount.setText(String.valueOf(GrandTotal));
        
        }
               catch(Exception ex)
               {
                   JOptionPane.showMessageDialog(null, "Please Check Details!!!","Warining",JOptionPane.WARNING_MESSAGE);
                   sgst.setText("0");
               }     
       
       }  
              
    }//GEN-LAST:event_sgstActionPerformed

    private void cgstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cgstKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cgstKeyPressed

    private void ratepertripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratepertripActionPerformed
        // TODO add your handling code here:
        String rateperTrip = ratepertrip.getText();
        if(ratepertrip.getText().isEmpty() && rateperTrip.matches("^[0-9]*$"))
            {
                JOptionPane.showMessageDialog(null,"Enter Correct Rate!!");
            }
            else
            {
                try
                {
        int trip = Integer.parseInt(totaltrip.getText().toString());
        int ratetrip =Integer.parseInt(ratepertrip.getText());
        
        int total = trip * ratetrip ;
        
        amount.setText(String.valueOf(total));
        grandAmount.setText(String.valueOf(total));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Please Check Details!!","warining",JOptionPane.WARNING_MESSAGE);
        }
    }
                
    }//GEN-LAST:event_ratepertripActionPerformed

    private void cgstamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgstamtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cgstamtActionPerformed

    private void grandAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandAmountActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_grandAmountActionPerformed

    private void cgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgstActionPerformed
        // TODO add your handling code here:
        String CGST = cgst.getText();
        
         if( cgst.getText().isEmpty()&& CGST.matches("^[0-9]*$") && amount.getText().isEmpty() && sgst.getText().isEmpty() )
           {
               JOptionPane.showMessageDialog(null,"Please check Details");
               
           }
           else
           {
               try{
        int Cgst= Integer.parseInt(cgst.getText());
        int AMOUNT = Integer.parseInt(amount.getText());
        int Sgst= Integer.parseInt(sgst.getText());
       
        int GrandTotal = Integer.parseInt(grandAmount.getText());
        
        int sgstAmount = (AMOUNT * Sgst) /100;
        sgstamt.setText(String.valueOf(sgstAmount));
        GrandTotal = AMOUNT + sgstAmount;
        grandAmount.setText(String.valueOf(GrandTotal));
        
        int cgstAmount = (AMOUNT * Cgst) /100;
        cgstamt.setText(String.valueOf(cgstAmount));
        GrandTotal = AMOUNT + cgstAmount + sgstAmount;
        grandAmount.setText(String.valueOf(GrandTotal));
        
         }
       catch(Exception ex)
       {
          JOptionPane.showMessageDialog(null, "Plese Check Details!!","Warning",JOptionPane.WARNING_MESSAGE);
          cgst.setText("0");
       }
       }  
        
    }//GEN-LAST:event_cgstActionPerformed

    private void toKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_toKeyTyped

    private void contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if(!(Character.isDigit(TestChar)))
        evt.consume();
        
    }//GEN-LAST:event_contactKeyTyped

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_contactActionPerformed

    private void ratepertripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ratepertripKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if(!(Character.isDigit(TestChar)))
        evt.consume();
    }//GEN-LAST:event_ratepertripKeyTyped

    private void vehiclecodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vehiclecodeKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_vehiclecodeKeyTyped

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        homepage homepage = new homepage();
        homepage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void vehiclecodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vehiclecodeKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() ==KeyEvent.VK_ENTER){
            String vehicleCode = vehiclecode.getText();
            
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/milind?autoRecoonect=true&useSSL=false","root","");
                insert = con.prepareStatement("select * from vehicle where code=?");
                
                insert.setString(1, vehicleCode);
                rs= insert.executeQuery();
                
                if(rs.next()== false){
                    JOptionPane.showMessageDialog(this, "Can Not Find the Vehicle !!");
                    vehicleno.setText("");
                }
                else{
                    String Number = rs.getString("number");
                    vehicleno.setText(Number.trim());
                }
            }
            catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehicle.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) {
            java.util.logging.Logger.getLogger(vehicle.class.getName()).log(Level.SEVERE, null, ex);
        }  
        }
    }//GEN-LAST:event_vehiclecodeKeyPressed
     public boolean emptyvalue(){
         if(id.getText().isEmpty() | to.getText().isEmpty() | contact.getText().isEmpty() | address.getText().isEmpty() | gstno.getText().isEmpty()  | grandAmount.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Please Fill Required Data!!","warning",JOptionPane.WARNING_MESSAGE);
             return false;
         }
         return true;
     }
     
     
    public boolean contactvalidate(){
        String Contact = contact.getText();
         if(Contact.matches("^[0-9]*$") && Contact.length()==10){
             return true;
         }
         else{
             JOptionPane.showMessageDialog(this, "Envalid Contact number!!","warning",JOptionPane.WARNING_MESSAGE);
             return false;
         }
    }
    public void clear(){
        auto_id();
        to.setText("");
        contact.setText("");
        address.setText("");
        date.setDate(null);
        challan.setText("");
        vehiclecode.setText("");
        vehicleno.setText("");
        gstno.setText("");
        ratepertrip.setText("");
        amount.setText("");
        totaltrip.setText("0");
        sgst.setText("0");
        sgstamt.setText("");
        cgst.setText("0");
        cgstamt.setText("");
        grandAmount.setText("");   
    }
    private void sgstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sgstFocusGained
        // TODO add your handling code here:
        if(sgst.getText().equals(("0"))){
            sgst.setText("");
            
        }
    }//GEN-LAST:event_sgstFocusGained

    private void sgstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sgstFocusLost
        // TODO add your handling code here:
        if(sgst.getText().equals("")){
            sgst.setText("0");
            
        }
    }//GEN-LAST:event_sgstFocusLost

    private void cgstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cgstFocusGained
        // TODO add your handling code here:
        if(cgst.getText().equals("0")){
         cgst.setText("");
    }
    }//GEN-LAST:event_cgstFocusGained

    private void cgstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cgstFocusLost
        // TODO add your handling code here:
        if(cgst.getText().equals("")){
         cgst.setText("0");
    }
    }//GEN-LAST:event_cgstFocusLost

    private void totaltripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltripActionPerformed
        // TODO add your handling code here:
        
        if(totaltrip.getText().isEmpty() || ratepertrip.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter the Rate Of Trip or Check The Operation!!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
        int trip = Integer.parseInt(totaltrip.getText().toString());
        int ratetrip =Integer.parseInt(ratepertrip.getText().toString()); 
      
        int total = trip * ratetrip ;
        
        amount.setText(String.valueOf(total)); 
        grandAmount.setText(String.valueOf(total));
        } 
    }//GEN-LAST:event_totaltripActionPerformed

    private void totaltripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totaltripKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if(!(Character.isDigit(TestChar)))
        evt.consume();
    }//GEN-LAST:event_totaltripKeyTyped

    private void totaltripFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totaltripFocusGained
        // TODO add your handling code here:
        if(totaltrip.getText().equals("0")){
            totaltrip.setText("");
        }
    }//GEN-LAST:event_totaltripFocusGained

    private void totaltripFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totaltripFocusLost
        // TODO add your handling code here:
        if(totaltrip.getText().equals("")){
            totaltrip.setText("0");
        }
    }//GEN-LAST:event_totaltripFocusLost

    private void challanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_challanKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if(!(Character.isDigit(TestChar)))
        evt.consume();
    }//GEN-LAST:event_challanKeyTyped

    private void sgstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sgstKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if(!(Character.isDigit(TestChar)))
        evt.consume();
    }//GEN-LAST:event_sgstKeyTyped

    private void cgstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cgstKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if(!(Character.isDigit(TestChar)))
        evt.consume();
        
    }//GEN-LAST:event_cgstKeyTyped

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        clear();
        billtxt.setText("");
        auto_id();
       
        
    }//GEN-LAST:event_resetActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
      
        if(emptyvalue() & contactvalidate()){
       
            billtxt.append("\t\t NARAYAN TRASNPORT \n\n"
                + "\tEarth Filling, Specialist in Rabbit & Murum, JCB,Dumper Supplier\n"
                +"                            Sai Niketan Co-op.Hsg Society,Nr.Omega English High School,"
                + "\n \t                           Khindipada,Bhandup(w)400082."
                + "\n===============================================================================================\n"
                + "Bill Id :"+ id.getText()+"\t\t\t"+autodate.getText()+"\t"+time.getText()
                +"\n\n==============================================================================================\n"
                        + "Customer Name:-"+to.getText()+"\t Mob:-"+contact.getText()+"\n Address:-"+address.getText()+"\n GSTIN :-"+gstno.getText()+
                "\n\n===============================================================================================\n"
                        + "\tDate\t"+date.getDate().toString()
                +"\n\tChallan No.  \t"+challan.getText()
                +"\n\tVehicle No.  \t"+vehicleno.getText()
                +"\n\tRate/Trip  \t"+ratepertrip.getText()
                +"\n\tTotal Trip  \t"+totaltrip.getText()
                +"\n\tAmount   \t"+amount.getText()
                +"\n-----------------------------------------------------------------------------------------------------------------------------------------------------\n"
                        + "\tSGST :\t"+sgst.getText()+"%\t"+"Amount :\t"+sgstamt.getText()+".rs\n"
                         + "\tCGST :\t"+cgst.getText()+"%\t"+"Amount :\t"+cgstamt.getText()+".rs\n"
               +"--------------------------------------------------------------------------------------------------------------------------------------------------------\n" 
               +"\tGrand Amount :\t\t"+grandAmount.getText()+" .rs"
               +"\n\n-----------------------------------------------------------------------------------------------------------------------------------------------------\n"
                       + "Bank : ABCD Bank\n"
                       + "A/C No: xxxxxxxxxxx\n"
                       + "IFSC no: XXXX123\n"
                       + "GSTIN No: ABCDEF123456\n\n"
                       + "\t\t\t       NARAYAN TRANSPORT"
                       + "\n-----------------------------------------------------------------------------------------------------------------------------------------------------\n"
                       + "\t\tTHANK YOU !!!!!" 
               
        ); 
           
            try {
                billtxt.print();
                
            } catch (PrinterException ex) {
                Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Reocrd Printed!!!");
            clear();
            billtxt.setText("");
            auto_id();
        }
    }//GEN-LAST:event_printActionPerformed

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        // TODO add your handling code here:
        
        if(search.getText().equals(("Search by Name")))
        {
            search.setText("");
        }
    }//GEN-LAST:event_searchFocusGained

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        // TODO add your handling code here:
        if(search.getText().equals(""))
        {
            search.setText("Search by Name");
        }
    }//GEN-LAST:event_searchFocusLost

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        
        
        
        if(search.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Record Not Found!!","warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
        
        try{
          Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/milind?autoRecoonect=true&useSSL=false","root","");
          insert = con.prepareStatement("SELECT * FROM record WHERE customerName=?");
          String name = search.getText();
          insert.setString(1, name);
          rs = insert.executeQuery();
          if(rs.next()==false){
              JOptionPane.showMessageDialog(this, "Record Can Not Found!!","Warning",JOptionPane.WARNING_MESSAGE);
              clear(); 
              search.setText("Search by Name");
          }
          else{
              id.setText(rs.getString("id"));
              to.setText(rs.getString("customerName"));
              contact.setText(rs.getString("contact"));
              address.setText(rs.getString("address"));
              gstno.setText(rs.getString("gst"));
              
             String date1=(String)rs.getString("date");
             Date Date1 = new SimpleDateFormat("dd/MM/yyyy").parse(date1);
             date.setDate(Date1);
              
              
              challan.setText(rs.getString("challan"));
              vehiclecode.setText(rs.getString("vehiclecode"));
              vehicleno.setText(rs.getString("vehicleno"));
              ratepertrip.setText(rs.getString("ratepertrip"));
              totaltrip.setText(rs.getString("totaltrip"));
              amount.setText(rs.getString("subamount"));
              sgst.setText(rs.getString("sgst"));
              sgstamt.setText(rs.getString("sgstamt"));
              cgst.setText(rs.getString("cgst"));
              cgstamt.setText(rs.getString("cgstamt"));
              grandAmount.setText(rs.getString("grandamount"));
              
              search.setText("Search by Name");
              
          }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (ParseException ex) {
                Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        if(to.getText().isEmpty()|address.getText().isEmpty() | contact.getText().isEmpty() | challan.getText().isEmpty() | gstno.getText().isEmpty() | totaltrip.getText().isEmpty() | ratepertrip.getText().isEmpty()
                |amount.getText().isEmpty()|cgst.getText().isEmpty()|cgstamt.getText().isEmpty()|sgst.getText().isEmpty() | sgstamt.getText().isEmpty() | grandAmount.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Please Search Record First!!","warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
           int ID = Integer.parseInt(id.getText().toString());
        try {
           Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/milind?autoRecoonect=true&useSSL=false","root","");
            insert = con.prepareStatement("DELETE FROM record WHERE id=?" );
            insert.setInt(1, ID);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Deleted!!!");
            auto_id();
            clear();
            to.requestFocus();
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if(to.getText().isEmpty()|address.getText().isEmpty() | challan.getText().isEmpty() | gstno.getText().isEmpty() | totaltrip.getText().isEmpty() | ratepertrip.getText().isEmpty()
                |amount.getText().isEmpty()|cgst.getText().isEmpty()|cgstamt.getText().isEmpty()|sgst.getText().isEmpty() | sgstamt.getText().isEmpty() | grandAmount.getText().isEmpty()| contact.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Please Search The Record First!!","warning",JOptionPane.WARNING_MESSAGE);
            clear();
            auto_id();
            to.requestFocus();
        }
        else
        {
            
        String Name = to.getText();
        String Address = address.getText();
        String Contact = contact.getText();
        String GSTIN = gstno.getText();
        String Challan = challan.getText();
        SimpleDateFormat Dformat = new SimpleDateFormat("dd/MM/yyy");
        String Date = Dformat.format(date.getDate());
        String VehicleCode = vehiclecode.getText();
        String VehicleNumber = vehicleno.getText();
        String TotalTrip = totaltrip.getText();
        String RatePerTrip = ratepertrip.getText();
        String SubAmount = amount.getText();
        String SGST = sgst.getText();
        String SGSTAmt = sgstamt.getText();
        String Cgst = cgst.getText();
        String CgstAmt = cgstamt.getText();
        String GrandTotal = grandAmount.getText();
        
        
    
            int ID = Integer.parseInt(id.getText());
            
            try{
                Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/milind?autoRecoonect=true&useSSL=false","root","");
            insert = con.prepareStatement("update record SET customerName=?,contact=?,address=?,gst=?,date=?,challan=?,vehiclecode=?,vehicleno=?,ratepertrip=?,totaltrip=?,subamount=?,sgst=?,sgstamt=?,cgst=?,cgstamt=?,grandamount=? where id=?" );
             
            insert.setString(1, Name);
            insert.setString(2, Contact);
            insert.setString(3, Address);
            insert.setString(4, GSTIN);
            insert.setString(5, Date);
            insert.setString(6, Challan);
            insert.setString(7, VehicleCode);
            insert.setString(8, VehicleNumber);
            insert.setString(9, RatePerTrip);
            insert.setString(10, TotalTrip);
            insert.setString(11, SubAmount);
            insert.setString(12, SGST);
            insert.setString(13, SGSTAmt);
            insert.setString(14, Cgst);
            insert.setString(15, CgstAmt);
            insert.setString(16, GrandTotal);
            insert.setInt(17, ID);
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Record Updated!!");
            auto_id();
            clear();
            to.requestFocus();
            
            }
             catch (ClassNotFoundException ex) {
            Logger.getLogger(vehicle.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        }
        
    }//GEN-LAST:event_updateActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel autodate;
    private javax.swing.JTextArea billtxt;
    private javax.swing.JTextField cgst;
    private javax.swing.JTextField cgstamt;
    private javax.swing.JTextField challan;
    private javax.swing.JTextField contact;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton delete;
    private javax.swing.JTextField grandAmount;
    private javax.swing.JTextField gstno;
    private javax.swing.JButton home;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print;
    private javax.swing.JTextField ratepertrip;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField sgst;
    private javax.swing.JTextField sgstamt;
    private javax.swing.JLabel time;
    private javax.swing.JTextField to;
    private javax.swing.JTextField totaltrip;
    private javax.swing.JButton update;
    private javax.swing.JTextField vehiclecode;
    private javax.swing.JTextField vehicleno;
    // End of variables declaration//GEN-END:variables
}
